export default {

    CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',

    BOOKMARKS_RECEIVED: 'BOOKMARKS_RECEIVED',

    PROFILES_RECEIVED: 'PROFILES_RECEIVED',
    PROFILE_CREATED: 'PROFILE_CREATED',
    PROFILE_SELECTED: 'PROFILE_SELECTED'

}